{
 "title": "Solana | Let's Node",
 "description": "Dashboard for Solana node",
 "tags": [
  "Linux",
  "Ubuntu",
  "Server",
  "Telegraf",
  "InfluxDB",
  "Docker",
  "Service file"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "influxdb" },
   {
    "name": "host",
    "label": "Host",
    "query": "SHOW TAG VALUES FROM \"system\" WITH KEY = \"host\""
   },
   {
    "name": "drive",
    "label": "Drives for IO/s",
    "query": "SHOW TAG VALUES FROM \"disk\" WITH KEY = \"device\""
   }
  ]
 },
 "panels": [
  {
   "title": "All servers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    { "title": "All servers", "type": "table", "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 } }
   ]
  },
  { "title": "Quick summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "CPU usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT 1-last(\"usage_idle\")+100 AS \"used_percent\" FROM \"cpu\" WHERE \"host\" =~ /^$host$/ AND \"cpu\" =~ /^cpu-total$/ AND $timeFilter fill(null)"
    }
   ]
  },
  {
   "title": "CPUs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"n_cpus\") AS \"n_cpus\" FROM \"system\" WHERE \"host\" =~ /^$host$/ AND $timeFilter fill(null)"
    }
   ]
  },
  {
   "title": "RAM usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"used_percent\") AS \"used_percent\" FROM \"mem\" WHERE \"host\" =~ /^$host$/ AND $timeFilter fill(null)"
    }
   ]
  },
  {
   "title": "RAM total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 9, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "SELECT last(\"total\") AS \"total\" FROM \"mem\" WHERE \"host\" =~ /^$host$/ AND $timeFilter fill(null)"
    }
   ]
  },
  {
   "title": "Drive usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 13, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"used_percent\") AS \"used_percent\" FROM \"disk\" WHERE (\"host\" =~ /^$host$/ AND \"path\" =~ /^\\/$/) AND $timeFilter fill(null)"
    }
   ]
  },
  {
   "title": "Drive total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "SELECT last(\"total\") AS \"total\" FROM \"disk\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter fill(null)"
    }
   ]
  },
  {
   "title": "Swap usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 19, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"used_percent\") AS \"used_percent\" FROM \"swap\" WHERE \"host\" =~ /^$host$/ AND $timeFilter fill(null)"
    }
   ]
  },
  {
   "title": "Swap total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "SELECT last(\"total\") AS \"total\" FROM \"swap\" WHERE \"host\" =~ /^$host$/ AND $timeFilter fill(null)"
    }
   ]
  },
  {
   "title": "Load average (15m)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"load15\") AS \"load15\" FROM \"system\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval) fill(null)"
    }
   ]
  },
  {
   "title": "RAM used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "SELECT last(\"used\") AS \"used\" FROM \"mem\" WHERE \"host\" =~ /^$host$/ AND $timeFilter fill(null)"
    }
   ]
  },
  {
   "title": "Drive used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "SELECT last(\"used\") AS \"used\" FROM \"disk\" WHERE \"host\" =~ /^$host$/ AND $timeFilter fill(null)"
    }
   ]
  },
  {
   "title": "Swap used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "SELECT last(\"used\") AS \"total\" FROM \"swap\" WHERE \"host\" =~ /^$host$/ AND $timeFilter fill(null)"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 1, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"uptime\") AS \"uptime\" FROM \"system\" WHERE \"host\" =~ /^$host$/ AND $timeFilter fill(null)"
    }
   ]
  },
  {
   "title": "Users",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 5, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"n_users\") AS \"n_users\" FROM \"system\" WHERE \"host\" =~ /^$host$/ AND $timeFilter fill(null)"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 9, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"total\") AS \"total\" FROM \"processes\" WHERE \"host\" =~ /^$host$/ AND $timeFilter fill(null)"
    }
   ]
  },
  {
   "title": "Docker running containers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 13, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"n_containers_running\") AS \"n_containers_running\" FROM \"docker\" WHERE \"host\" =~ /^$host$/ AND $timeFilter fill(null)"
    }
   ]
  },
  {
   "title": "Download",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 17, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT non_negative_derivative(last(\"bytes_recv\"), 1s)*8 AS \"download\" FROM \"net\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval) fill(null)"
    }
   ]
  },
  {
   "title": "Upload",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 21, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT non_negative_derivative(last(\"bytes_sent\"), 1s)*8 AS \"upload\" FROM \"net\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval) fill(null)"
    }
   ]
  },
  { "title": "Quick node info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Current epoch",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 1, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT epoch, last(\"epoch_progress\") AS \"epoch_progress\" FROM \"solana\" WHERE \"host\" =~ /^$host$/ AND $timeFilter fill(null)"
    }
   ]
  },
  {
   "title": "Epoch progress",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"epoch_progress\") AS \"epoch_progress\" FROM \"solana\" WHERE \"host\" =~ /^$host$/ AND $timeFilter fill(null)"
    }
   ]
  },
  {
   "title": "Epoch end time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 5, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"epoch_end_time\") AS \"epoch_end_time\" FROM \"solana\" WHERE \"host\" =~ /^$host$/ AND $timeFilter fill(null)"
    }
   ]
  },
  {
   "title": "Next leader slot",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 9, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"leader_slot_time\") AS \"leader_slot_time\" FROM \"solana\" WHERE \"host\" =~ /^$host$/ AND $timeFilter fill(null)"
    }
   ]
  },
  {
   "title": "Node status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 11, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"status\") AS \"status\" FROM \"solana\" WHERE \"host\" =~ /^$host$/ AND $timeFilter fill(null)"
    }
   ]
  },
  {
   "title": "Node version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 13, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"version\") AS \"version\" FROM \"solana\" WHERE \"host\" =~ /^$host$/ AND $timeFilter fill(null)"
    }
   ]
  },
  {
   "title": "Validator commission",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 17, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"validator_commission\") AS \"validator_commission\" FROM \"solana\" WHERE \"host\" =~ /^$host$/ AND $timeFilter fill(null)"
    }
   ]
  },
  {
   "title": "Identity account balance",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 19, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"identity_balance\") AS \"identity_balance\" FROM \"solana\" WHERE \"host\" =~ /^$host$/ AND $timeFilter fill(null)"
    }
   ]
  },
  {
   "title": "Vote account balance",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 21, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"vote_balance\") AS \"vote_balance\" FROM \"solana\" WHERE \"host\" =~ /^$host$/ AND $timeFilter fill(null)"
    }
   ]
  },
  {
   "title": "Information by epoch",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "SELECT last(\"solana_price\") AS \"solana_price\", \"total_slots\", \"passed_slots\", \"skipped_slots\", \"validator_skip_rate\", \"cluster_skip_rate\", \"credits\", \"stake\", \"stake_reward\" + \"slot_rewards\" AS rewards, \"costs\", \"profit\", \"profit_usd\" FROM \"solana\" WHERE \"host\" =~ /^$host$/ GROUP BY \"epoch\" fill(null)\n"
    }
   ]
  },
  { "title": "Node info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Skip rate",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT last(\"validator_skip_rate\") AS \"Validator\", \"cluster_skip_rate\" AS \"Cluster\" FROM \"solana\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Slots",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT last(\"passed_slots\") AS \"Passed\", \"skipped_slots\" AS \"Skipped\" FROM \"solana\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Credits",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT last(\"credits\") AS \"Credits\" FROM \"solana\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Balances",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT last(\"identity_balance\") AS \"Identity account\", \"vote_balance\" AS \"Vote account\" FROM \"solana\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Docker",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "collapsed": true,
   "panels": [
    {
     "title": "Containers",
     "type": "table",
     "gridPos": { "h": 13, "w": 10, "x": 0, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "$col",
       "query": "SELECT \"container_image\", \"container_status\", last(\"uptime_ns\")/1000000000 AS \"uptime\" FROM \"docker_container_status\" WHERE \"host\" =~ /^$host$/ AND time >= $__to*1000000 - 1m GROUP BY \"container_name\" fill(none)\n"
      }
     ]
    },
    {
     "title": "CPU usage",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 7, "x": 10, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "alias": "$tag_container_name",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "cpu",
       "query": "SELECT last(\"usage_percent\") AS \"usage_percent\" FROM \"docker_container_cpu\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval), \"container_name\" fill(none)",
       "select": [
        [
         { "params": [ "usage_user" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "RAM usage",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 7, "x": 17, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "alias": "$tag_container_name",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "cpu",
       "query": "SELECT last(\"usage\") AS \"usage\" FROM \"docker_container_mem\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval), \"container_name\" fill(none)",
       "select": [
        [
         { "params": [ "usage_user" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Selected processes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 },
   "collapsed": true,
   "panels": [
    {
     "title": "Processes",
     "type": "table",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "$col",
       "query": "SELECT \"process_name\", \"user\", last(\"cpu_usage\") AS \"cpu_usage\", \"memory_usage\" FROM \"procstat\" WHERE \"host\" =~ /$host$/ AND time >= $__to*1000000 - 1m GROUP BY \"pid\"::tag fill(null)"
      }
     ]
    },
    {
     "title": "Enabled systemd units",
     "type": "table",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "$col",
       "query": "SELECT \"load\", \"active\", last(\"sub_code\") AS \"sub_code\" FROM \"systemd_units\" WHERE \"host\" =~ /$host$/ AND time >= $__to*1000000 - 1m GROUP BY \"name\" fill(null)"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU of total",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "cpu",
       "query": "SELECT last(\"usage_user\") AS \"User\", last(\"usage_system\") AS \"System\" FROM \"cpu\" WHERE \"host\" =~ /^$host$/ AND \"cpu\" =~ /^cpu-total$/ AND $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "usage_user" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Load average",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "cpu",
       "query": "SELECT last(\"load1\") AS \"1 min\", last(\"load5\") AS \"5 min\", last(\"load15\") AS \"15 min\" FROM \"system\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "usage_user" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "CPU per core",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "alias": "$tag_cpu",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "cpu",
       "query": "SELECT 100 - last(\"usage_idle\") AS \"used_percent\" FROM \"cpu\" WHERE \"host\" =~ /^$host$/ AND \"cpu\" =~ /cpu[0-9].*/ AND $timeFilter GROUP BY time($interval), \"cpu\" fill(null)",
       "select": [
        [
         { "params": [ "usage_user" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "RAM, SWAP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 },
   "collapsed": true,
   "panels": [
    {
     "title": "RAM usage",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "bits" } },
     "targets": [
      {
       "alias": "Used",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "cpu",
       "query": "SELECT last(\"used\") AS \"used\" FROM \"mem\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "usage_user" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Swap used",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "bits" } },
     "targets": [
      {
       "alias": "Used",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "cpu",
       "query": "SELECT last(\"used\") AS \"used\" FROM \"swap\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "usage_user" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Drive",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 },
   "collapsed": true,
   "panels": [
    {
     "title": "Drive usage",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "alias": "Used",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "cpu",
       "query": "SELECT last(\"used\") AS \"used\" FROM \"disk\" WHERE \"host\" =~ /^$host$/ AND $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "usage_user" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Drive IO/s",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "alias": "$tag_name: $col",
       "query": "SELECT derivative(last(\"reads\"), 1s) AS \"read\", derivative(last(\"writes\"), 1s) AS \"write\" FROM \"diskio\" WHERE \"host\" =~ /^$host$/ AND \"name\" =~ /^$drive$/ AND $timeFilter GROUP BY time($interval), \"name\" fill(null)"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network usage",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "alias": "$tag_interface: $col",
       "function": "derivative",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "interface", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "net_bytes_recv",
       "query": "SELECT non_negative_derivative(last(bytes_recv),1s)*8 as \"download\", non_negative_derivative(last(bytes_sent),1s)*8 as \"upload\"  FROM \"net\" WHERE \"host\" =~ /$host/ AND $timeFilter GROUP BY time($interval), * fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Traffic used",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "alias": "$tag_interface: $col",
       "function": "derivative",
       "groupBy": [
        { "interval": "auto", "params": [ "auto" ], "type": "time" },
        { "key": "host", "params": [ "tag" ], "type": "tag" },
        { "key": "interface", "params": [ "tag" ], "type": "tag" }
       ],
       "measurement": "net_bytes_recv",
       "query": "SELECT last(bytes_recv) as \"in\", last(bytes_sent) as \"out\"  FROM \"net\" WHERE \"host\" =~ /$host/ AND $timeFilter GROUP BY time($interval), * fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  { "title": "Help information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Help information",
   "type": "text",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 61 },
   "options": {
    "content": "# Useful links\n\n <a href=\"https://t.me/letskynode\" target=\"_blank\">Let’s Node!</a> — node community, dashboard creating\n\n <a href=\"https://teletype.in/@letskynode/1_Monitoring_installation\" target=\"_blank\">Russian-language monitoring guide</a>\n\n <a href=\"https://teletype.in/@letskynode/Staking_EN\" target=\"_blank\">Crypto staking (EN)</a>\n\n <a href=\"https://teletype.in/@letskynode/Staking\" target=\"_blank\">Crypto staking (RU)</a>\n\n <a href=\"https://teletype.in/@letskynode/thankyou\" target=\"_blank\">Crypto donations</a>\n\n# Terms\n\n- DS — data source\n\n# A server table\n⠀To add all servers from DS to the servers table you need:\n- Add DS to Grafana configuration («Configuration» — «Data sources» — «Add data source»);\n- Open the dashboard;\n- Click the table header — «Edit»;\n- In the «Query» tab select «Data source» — «Mixed»;\n- Click «+ Query»;\n- Select the desired DS;\n- Paste query:\n\n```sql\nSELECT \"ip\", \"n_cpus\", \"ram_total\", \"drive_total\", \"load15\", \"cpu_usage_percent\", \"ram_used_percent\", last(\"drive_used_percent\") AS \"drive_used_percent\" FROM \"for_table\" WHERE $timeFilter GROUP BY \"host\"\n\n```\n\n- Select «Table» in the «Format as» value;\n- Click «Apply» to save the panel;\n- Click the floppy disk icon button on the top right to save dashboard changes."
   }
  }
 ]
}